### ISSUE TITLE
argv help menu

### ISSUE THREAD

**Issue by CallumBeaney** [nate-sys/tuime#4]
There's a large number of options for different fonts, colours etc, and command-line args are case-dependent e.g. `red` is illegal because the arg must be `Red` . An in-built sub-menu to tell users options in addition to general flag syntax would be a big QOL improvement as otherwise many features will likely be ignored.

**Comment by nthnd** [comment]
I've added a better help output and lowercased all args before parsing so I hope this is fixed!
