### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by mainsm** [nate-sys/tuime#5]
I ran Tuime with the format showing hours minutes and seconds.  It's now very hard not to notice that the terminal will flash to blank for a split second while refreshing the time.

**Comment by nthnd** [comment]
What terminal are you running? It refreshes smoothly on my Alacritty and Wezterm builds.

**Comment by mainsm** [comment]
This is going to sound stupid, but I'm using WSL in Windows Terminal.
TTY-clock works just fine though.

**Comment by nthnd** [comment]
Can you check the latest build?

**Comment by mainsm** [comment]
I just installed it with cargo. Unfortunately it's still flickering every
second. I wouldn't worry too much about it.  It could be a problem with my
terminal since I'm using WSL.

**Comment by a-usr** [comment]
@mainsm the issue should be fixed for good with the current code base. If want you can clone the repo and build locally.

**Comment by mainsm** [comment]
> @mainsm the issue should be fixed for good with the current code base. If want you can clone the repo and build locally.
> 

It's perfect
